apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: receiver
  labels:
    k8s-app: receiver
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: receiver
  template:
    metadata:
      labels:
        k8s-app: receiver
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
      - name: receiver
        image: kairen/receiver-armhf:1.0.1
        env:
         - name: K8S_API_SERVER_IP
           value: "172.20.3.27"
         - name: REMOTE_MQTT_IP
           value: "172.20.3.21"
         - name: MQTT_PUB_TOPIC
           value: "Cloud"
         - name: DEBUG
           value: "True"
         - name: SERVICE_NAME
           value: "emqtt"
         - name: POD_NAME
           valueFrom:
             fieldRef:
               fieldPath: metadata.name
         - name: POD_NAMESPACE
           valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
