apiVersion: v1
kind: Service
metadata:
  name: receiver
  labels:
    k8s-app: receiver
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: receiver
  ports:
  - name: receiver
    protocol: TCP
    port: 8889
    targetPort: 8889
